#!/bin/bash

# Lista extensa de frases inspiradas en los primeros chatbots
texts=(
"Hola, ¿cómo estás?"
"Estoy aquí para ayudarte."
"Cuéntame más sobre eso."
"¿Qué te trae por aquí hoy?"
"Eso suena interesante, dime más."
"¿Por qué piensas eso?"
"Entiendo, ¿y cómo te sientes al respecto?"
"¿Qué crees que deberíamos hacer ahora?"
"Estoy aquí para escucharte."
"Eso debe ser difícil para ti."
"¿Cómo te puedo ayudar hoy?"
"Por favor, continúa, estoy escuchando."
"¿Qué piensas de eso?"
"¿Te gustaría explorar eso más a fondo?"
"Cuéntame más sobre lo que sientes."
"Eso es muy interesante, ¿puedes explicarlo más?"
"Estoy aprendiendo mucho de ti."
"¿Qué te gustaría hablar conmigo?"
"¡Qué fascinante!"
"¿Cómo puedo mejorar tu día?"
"No estoy seguro de entender, ¿puedes elaborarlo?"
"Es agradable tener esta conversación contigo."
"¿Qué significa eso para ti?"
"Eso tiene sentido, ¿quieres profundizar en ello?"
"Me alegra que compartas esto conmigo."
"Siempre estoy aquí para ti."
"¿Qué harías en una situación como esta?"
"Gracias por compartir esto conmigo."
"¿Cómo te sientes al respecto?"
"Eso debe ser complicado, ¿verdad?"
"Cuéntame más sobre tus pensamientos."
"¿Qué esperas lograr con esto?"
"Eso suena como un desafío."
"¿Te ha pasado algo parecido antes?"
"Es importante considerar todas las opciones."
"Estoy aquí para apoyarte en lo que necesites."
"Eso es muy interesante, ¿cómo lo descubriste?"
"¿Te gustaría cambiar algo en esta situación?"
"¿Cómo puedo hacer que esto sea más útil para ti?"
"¿Qué te hizo llegar a esa conclusión?"
"Eso parece importante, ¿quieres profundizar?"
"Estoy curioso, cuéntame más."
"¿Cómo impacta esto en tu vida?"
"Eso debe haber sido una experiencia única."
"Gracias por confiar en mí con esta información."
"¿Qué opinas de las alternativas?"
"Estoy aquí para ayudarte a procesar esto."
"¿Qué piensas hacer a continuación?"
"Es interesante ver las cosas desde tu perspectiva."
"Siempre puedes contar conmigo para hablar."
"¿Qué has aprendido de esta experiencia?"
"Cuéntame, ¿cómo te hace sentir eso?"
"Eso es fascinante, ¿cómo llegaste a esta idea?"
"Es un placer escucharte."
"Estoy seguro de que encontrarás una solución."
"¿Qué significa eso para ti?"
"Estoy disfrutando nuestra conversación."
"Esto realmente me hace reflexionar."
"Es inspirador escuchar tu historia."
"Estoy aprendiendo algo nuevo de ti."
"¿Qué podemos hacer para avanzar?"
"¿Hay algo más que quieras compartir?"
"Gracias por tu tiempo y confianza."
)

# Ejecutar múltiples inserciones
for text in "${texts[@]}"; do
    echo "Insertando: $text"
    go run main.go -insert "$text"
done